version: "3"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ddueruem
      POSTGRES_PASSWORD: ddueruem
      POSTGRES_DB: ddueruem
    volumes:
      - postgresdata:/var/lib/postgresql

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - djangomedia:/api/media
    command: ./entrypoint.sh
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
    command: nginx -g 'daemon off;'

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgresdata:
  djangomedia:
  certbot: