version: "3"

services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command:
    #- "--log.level=DEBUG"
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.websecure.address=:443"
    - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    - "--certificatesresolvers.myresolver.acme.email=tobias.hess@uni-ulm.com"
    - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ddueruem
      POSTGRES_PASSWORD: ddueruem
      POSTGRES_DB: ddueruem
    volumes:
      - postgresdata:/var/lib/postgresql

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - djangomedia:/api/media
    command: ./entrypoint.sh
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
    command: nginx -g 'daemon off;'
<<<<<<< HEAD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`vm-154-210.bwcloud.uni-ulm.de`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
=======

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
>>>>>>> bb4277323f33f5a756d8d9b6a109dfbc1b3e215a

volumes:
  postgresdata:
  djangomedia: