name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: make env
        run: |
          mv '../backend/ddueruemweb/.env.testing' '../backend/ddueruemweb/.env'
          cat ../backend/ddueruemweb/.env

      - name: Install Dependencies
        run: |
          cd ../backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Migrations
        run: |
          cd ../backend
          python manage.py makemigrations
          python manage.py migrate --run-syncdb
          
      - name: Run Server
        run: |
          cd ../backend
          python manage.py runserver
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install serve
        run: npm install -g serve

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          build: npm run build
          start: serve dist -s -p 8080
