name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install serve
        run: npm install -g serve

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          build: npm run build
          start: serve dist -s -p 8080
