name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run:
          - npm install -g serve
          - npm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          build: npm run build
          start: node_modules/.bin/serve build -p 8080
