name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/src
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
